# vim: ft=zsh

HISTFILE=~/.cache/zsh_history
SAVEHIST=1000
HISTSIZE=$SAVEHIST
export HISTFILE SAVEHIST HISTSIZE

setopt EXTENDED_HISTORY
setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_REDUCE_BLANKS
